# constants from config file
MASTER_FABRIC_LIST_TABNAME = ''
VALIDATION_CELL_REF = ''
VALIDATION_CELL_VALUE = ''
CODE_CELL_REF = ''
CODE_CELL_VALUE = ''
DESCRIPTION_CELL_REF = ''
DESCRIPTION_CELL_VALUE = ''
BUZ_STARTING_ROW = 0
BUZ_PR_STARTING_ROW = 0
PELMETS_TAB_NAME = ''
PELMETS_TYPE = ''

# Buz inventory item columns
COL_PKID = ''
COL_INVENTORY_CODE = ''
COL_DESCRIPTION = ''
COL_SUPPLIER_CODE = ''
COL_SUPPLIER_PRODUCT_CODE = ''
COL_SUPPLIER_PRODUCT_DESCRIPTION = ''
COL_BRAND_NAME = ''
COL_BRAND_NAME_PELMETS = ''
COL_FABRIC_NAME = ''
COL_FABRIC_NAME_PELMETS = ''
COL_VERTICAL_PR = ''
COL_WIDTH = ''
COL_DIRECTION = ''
COL_OPERATION = ''

# Fabric Master List (FML) columns
COL_FML_BRAND_NAME = ''
COL_FML_FABRIC_NAME = ''
COL_FML_SUPPLIER_CODE = ''
COL_FML_VERTICAL_PR = ''
COL_FML_WIDTH = ''
COL_FML_DIRECTION = ''
COL_FML_COST = ''
COL_FML_COST_EFFECTIVE_FROM = ''

# Buz Pricing coefficient columns
COL_BPC_PKID = ''
COL_BPC_DESCRIPTION = ''
COL_BPC_INVENTORY_CODE = ''
COL_BPC_DATEFROM = ''
COL_BPC_SELLWIDE = ''
COL_BPC_SELLHEIGHT = ''
COL_BPC_COSTWIDE = ''
COL_BPC_COSTHEIGHT = ''
COL_BPC_OPERATION = ''

INVENTORY_DESCRIPTIONS = {
    'CURTNT': 'Curtain no track',
    'CURTWT': 'Curtain with track',
    'PELMDD': 'Padded Pelmet',
    'ROMNDC': 'Decorative Roman'}

